
const USER_ROLE_NAME = {
    ROLE_ADMIN: "ROLE_ADMIN",
    ROLE_OPERATOR: "ROLE_OPERATOR",
    ROLE_MAN_OFFICE: "ROLE_MAN_OFFICE",
    ROLE_SEC_OFFICE: "ROLE_SEC_OFFICE"
}

const USER_ROLE_PRIORITY = {
    ROLE_ADMIN: 10,
    ROLE_OPERATOR: 9,
    ROLE_MAN_OFFICE: 8,
    ROLE_SEC_OFFICE: 7
}
export { USER_ROLE_NAME, USER_ROLE_PRIORITY }
